/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appfresa.ventaview;

import appfresa.ventaservice.VentaService;

/**
 *
 * @author usuario
 */
public class VentaView extends javax.swing.JFrame {

    /**
     * Creates new form VentaView
     */
    public VentaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cajaprecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajacantcajas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaporcentaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cajagasto = new javax.swing.JTextField();
        cajaimporte = new javax.swing.JTextField();
        cajaganancia = new javax.swing.JTextField();
        cajapreciodeventa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jLabel1.setText("PRECIO X CAJA: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 140, 30);

        cajaprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaprecioActionPerformed(evt);
            }
        });
        getContentPane().add(cajaprecio);
        cajaprecio.setBounds(170, 70, 70, 30);

        jLabel2.setText("CANTIDAD DE CAJAS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 110, 14);

        cajacantcajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajacantcajasActionPerformed(evt);
            }
        });
        getContentPane().add(cajacantcajas);
        cajacantcajas.setBounds(170, 110, 70, 30);

        jLabel3.setText("PORCENTAJE DE GANANCIA: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 150, 14);
        getContentPane().add(cajaporcentaje);
        cajaporcentaje.setBounds(170, 150, 70, 30);

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 120, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("El gasto total es de: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 130, 30);

        cajagasto.setEditable(false);
        getContentPane().add(cajagasto);
        cajagasto.setBounds(210, 190, 110, 30);

        cajaimporte.setEditable(false);
        getContentPane().add(cajaimporte);
        cajaimporte.setBounds(210, 230, 110, 30);

        cajaganancia.setEditable(false);
        getContentPane().add(cajaganancia);
        cajaganancia.setBounds(210, 270, 110, 30);

        cajapreciodeventa.setEditable(false);
        getContentPane().add(cajapreciodeventa);
        cajapreciodeventa.setBounds(210, 310, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("El importe total es de:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 130, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("La ganancia total es de: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 275, 150, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Precio de venta x caja:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(44, 315, 150, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("APP DE AYUDA ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 10, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaprecioActionPerformed

    private void cajacantcajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajacantcajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajacantcajasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //variables
        double precioCaja, porcentajeGanancia, gastoTotal, ingresoTotal, ganancia, precioVentaCaja;
        int cantidadCajas;
        //datos
        precioCaja = Double.parseDouble(cajaprecio.getText());
        porcentajeGanancia = Double.parseDouble(cajaporcentaje.getText());
        cantidadCajas = Integer.parseInt(cajacantcajas.getText());
        //proceso
        VentaService service = new VentaService();
        gastoTotal = service.calcGastosTotales(cantidadCajas, precioCaja);
        ingresoTotal = service.calcIngresosTotales(gastoTotal, porcentajeGanancia);
        ganancia = service.calcGanancia(gastoTotal, ingresoTotal);
        precioVentaCaja = service.calcprecioVentaCaja(ingresoTotal, cantidadCajas);
        // Reporte
        cajagasto.setText("" + gastoTotal);
        cajaimporte.setText("" + ingresoTotal);
        cajaganancia.setText("" + ganancia);
        cajapreciodeventa.setText ("" + precioVentaCaja);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajacantcajas;
    private javax.swing.JTextField cajaganancia;
    private javax.swing.JTextField cajagasto;
    private javax.swing.JTextField cajaimporte;
    private javax.swing.JTextField cajaporcentaje;
    private javax.swing.JTextField cajaprecio;
    private javax.swing.JTextField cajapreciodeventa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
